export enum CardSuite {
    Two_Spade = 'Two_Spade',
    Three_Spade = 'Three_Spade',
    Four_Spade = 'Four_Spade',
    Five_Spade = 'Five_Spade',
    Six_Spade = 'Six_Spade',
    Seven_Spade = 'Seven_Spade',
    Eight_Spade = 'Eight_Spade',
    Nine_Spade = 'Nine_Spade',
    Ten_Spade = 'Ten_Spade',
    Jack_Spade = 'Jack_Spade',
    Queen_Spade = 'Queen_Spade',
    King_Spade = 'King_Spade',
    Ace_Spade = 'Ace_Spade',
    Two_Club = 'Two_Club',
    Three_Club = 'Three_Club',
    Four_Club = 'Four_Club',
    Five_Club = 'Five_Club',
    Six_Club = 'Six_Club',
    Seven_Club = 'Seven_Club',
    Eight_Club = 'Eight_Club',
    Nine_Club = 'Nine_Club',
    Ten_Club = 'Ten_Club',
    Jack_Club = 'Jack_Club',
    Queen_Club = 'Queen_Club',
    King_Club = 'King_Club',
    Ace_Club = 'Ace_Club',
    Two_Heart = 'Two_Heart',
    Three_Heart = 'Three_Heart',
    Four_Heart = 'Four_Heart',
    Five_Heart = 'Five_Heart',
    Six_Heart = 'Six_Heart',
    Seven_Heart = 'Seven_Heart',
    Eight_Heart = 'Eight_Heart',
    Nine_Heart = 'Nine_Heart',
    Ten_Heart = 'Ten_Heart',
    Jack_Heart = 'Jack_Heart',
    Queen_Heart = 'Queen_Heart',
    King_Heart = 'King_Heart',
    Ace_Heart = 'Ace_Heart',
    Two_Diamond = 'Two_Diamond',
    Three_Diamond = 'Three_Diamond',
    Four_Diamond = 'Four_Diamond',
    Five_Diamond = 'Five_Diamond',
    Six_Diamond = 'Six_Diamond',
    Seven_Diamond = 'Seven_Diamond',
    Eight_Diamond = 'Eight_Diamond',
    Nine_Diamond = 'Nine_Diamond',
    Ten_Diamond = 'Ten_Diamond',
    Jack_Diamond = 'Jack_Diamond',
    Queen_Diamond = 'Queen_Diamond',
    King_Diamond = 'King_Diamond',
    Ace_Diamond = 'Ace_Diamond',
}

export enum Card {
    Two = 'Two',
    Three = 'Three',
    Four = 'Four',
    Five = 'Five',
    Six = 'Six',
    Seven = 'Seven',
    Eight = 'Eight',
    Nine = 'Nine',
    Ten = 'Ten',
    Jack = 'Jack',
    Queen = 'Queen',
    King = 'King',
    Ace = 'Ace',
    Joker1 = 'Joker1',
    Joker2 = 'Joker2'
}

export type CardInADeck = CardSuite | Extract<Card, Card.Joker1 | Card.Joker2>

export enum Suite {
    Spade = 'Spade',
    Club = 'Club',
    Diamond = 'Diamond',
    Heart = 'Heart'
}

export const CardValue = {
    [CardSuite.Two_Spade]: 2,
    [CardSuite.Three_Spade]: 3,
    [CardSuite.Four_Spade]: 4,
    [CardSuite.Five_Spade]: 5,
    [CardSuite.Six_Spade]: 6,
    [CardSuite.Seven_Spade]: 7,
    [CardSuite.Eight_Spade]: 8,
    [CardSuite.Nine_Spade]: 9,
    [CardSuite.Ten_Spade]: 10,
    [CardSuite.Jack_Spade]: 10,
    [CardSuite.Queen_Spade]: 10,
    [CardSuite.King_Spade]: 0,
    [CardSuite.Ace_Spade]: 1,
    [CardSuite.Two_Club]: 2,
    [CardSuite.Three_Club]: 3,
    [CardSuite.Four_Club]: 4,
    [CardSuite.Five_Club]: 5,
    [CardSuite.Six_Club]: 6,
    [CardSuite.Seven_Club]: 7,
    [CardSuite.Eight_Club]: 8,
    [CardSuite.Nine_Club]: 9,
    [CardSuite.Ten_Club]: 10,
    [CardSuite.Jack_Club]: 10,
    [CardSuite.Queen_Club]: 10,
    [CardSuite.King_Club]: 0,
    [CardSuite.Ace_Club]: 1,
    [CardSuite.Two_Heart]: 2,
    [CardSuite.Three_Heart]: 3,
    [CardSuite.Four_Heart]: 4,
    [CardSuite.Five_Heart]: 5,
    [CardSuite.Six_Heart]: 6,
    [CardSuite.Seven_Heart]: 7,
    [CardSuite.Eight_Heart]: 8,
    [CardSuite.Nine_Heart]: 9,
    [CardSuite.Ten_Heart]: 10,
    [CardSuite.Jack_Heart]: 10,
    [CardSuite.Queen_Heart]: 10,
    [CardSuite.King_Heart]: 0,
    [CardSuite.Ace_Heart]: 1,
    [CardSuite.Two_Diamond]: 2,
    [CardSuite.Three_Diamond]: 3,
    [CardSuite.Four_Diamond]: 4,
    [CardSuite.Five_Diamond]: 5,
    [CardSuite.Six_Diamond]: 6,
    [CardSuite.Seven_Diamond]: 7,
    [CardSuite.Eight_Diamond]: 8,
    [CardSuite.Nine_Diamond]: 9,
    [CardSuite.Ten_Diamond]: 10,
    [CardSuite.Jack_Diamond]: 10,
    [CardSuite.Queen_Diamond]: 10,
    [CardSuite.King_Diamond]: 0,
    [CardSuite.Ace_Diamond]: 1,
    [Card.Joker1]: -2,
    [Card.Joker2]: -2
}